# 로컬
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username: sa

#jpa:
#  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  generate-ddl: false
#  defer-datasource-initialization: true
#  hibernate:
#    ddl-auto: none