# 로컬
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local;DB_CLOSE_DELAY=-1
    username: sa

  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
      show_sql: true